application: reciteconsole
version: 2
runtime: python
api_version: 1
default_expiration: "2d"

handlers:
- url: /staticfiles
  static_dir: staticfiles

- url: /favicon\.ico
  static_files: staticfiles/favicon.ico
  upload: staticfiles/favicon.ico

- url: /addrcword
  script: admin.py
  login: admin

- url: /chkrcword
  script: admin.py
  login: admin

- url: /dailyjobs
  script: admin.py
  login: admin

- url: /admin.*
  script: admin.py
  login: admin

- url: /m.*
  script: mobile.py

- url: /.*
  script: main.py
