application: reciteconsole
version: 2
runtime: python
api_version: 1

handlers:
- url: /staticfiles
  static_dir: staticfiles

- url: /favicon\.ico
  static_files: staticfiles/favicon.ico
  upload: staticfiles/favicon.ico

- url: /cleanup
  script: main.py
  login: admin

- url: /m/admin
  script: admin.py
  login: admin

- url: /m.*
  script: mobile.py

- url: /.*
  script: main.py
